### ISSUE TITLE
[HW] <NAME>

### ISSUE THREAD

**Issue by T1nyleo7** [datastaxdevs/workshop-spring-stargate#116]
**Name:** Mayra Sanchez
**Email:** m.snchz19@gmail.com
**Linkedin Profile:** <https://www.linkedin.com/in/mayra-sanchez-03906720b>

Attach the homework step I screenshots below:
-----------------------------------------
https://astra.datastax.com/org/5a41fb8e-35cc-4e41-8f23-511a9eda218e/database/1d4121b4-8393-44e7-9b04-6bca9ab28ef4/summary

https://8080-black-octopus-v4auucmc.ws-us16.gitpod.io/?planetName=Chulak

https://black-octopus-v4auucmc.ws-us16.gitpod.io/

Attach the homework step II screenshots below:
-----------------------------------------

![image](https://user-images.githubusercontent.com/89997486/133132006-d31d032a-2dfa-4d50-b8f0-f211dddaa9a8.png)

**Comment by SonicDMG** [comment]
Hi there Mayra, looks like you did everything, but did you have a screenshot of the completed screen from the spring scenario in step 2?

**Comment by T1nyleo7** [comment]
> Hi there Mayra, looks like you did everything, but did you have a screenshot of the completed screen from the spring scenario in step 2?

Hello, SonicDMG sorry for the late update.  I have completed part 2 spring scenario the same day as the class webinar lesson. Just finished adding the snapshot.

**Comment by HadesArchitect** [comment]
Hey **Mayra Sanchez**, great job! Congrats! Here is your badge! https://api.badgr.io/public/assertions/2-Ub4vxASuSNdS7971tkrg
