### ISSUE TITLE
[HW] <Workshop-spring-stargate>

### ISSUE THREAD

**Issue by guptap16** [datastaxdevs/workshop-spring-stargate#136]
**Name:** Priyanka
**Email:** pg160982@gmail.com
**Linkedin Profile:** https://www.linkedin.com/in/priyanka-gupta-csm-131a98156/

Attach the homework step I screenshots below:
-----------------------------------------

  
Attach the homework step II screenshots below:
-----------------------------------------

![final step ss](https://user-images.githubusercontent.com/34112794/132388524-1cdd96d8-83ed-40ce-8202-e175c5821231.JPG)
![url](https://user-images.githubusercontent.com/34112794/132388573-71168d77-985c-47e9-8061-4243bed608d4.JPG)

**Comment by SonicDMG** [comment]
Hey there Priyanka, thank you for your submission. Nice job getting the app correctly configured and deployed. The only thing we are missing is step 2 of the homework.
2. [Learn more about spring in the course](https://www.datastax.com/dev/spring) and complete scenario Build a Spring Boot REST Service at the bottom of the page and make a screenshot of the "congratulations" page.

Please post an image of the "completed" screen once finished.

**Comment by guptap16** [comment]
here is the screen shot of congratulations message after completion of step [2
![completed](https://user-images.githubusercontent.com/34112794/134827067-7c4920a2-674c-4a22-93a0-c1c269169e02.JPG)
].

**Comment by HadesArchitect** [comment]
Hey **Priyanka**, great job! Congrats! Here is your badge! https://api.badgr.io/public/assertions/AZTe_JIqSnuerA8Z85sQ3A
