### ISSUE TITLE
Raphael

### ISSUE THREAD

**Issue by raphaelgc** [datastaxdevs/workshop-spring-stargate#137]
**Name:** Raphael
**Email:** raphaelguterres@gmail.com
**Linkedin Profile:** www.linkedin.com/in/raphaelgc

Attach the homework step I screenshots below:
-----------------------------------------
![dtstx-spring2](https://user-images.githubusercontent.com/69475751/132432559-7e215fe2-e18d-4eda-a084-7f217a8062ea.jpg)
![dtstx-spring3](https://user-images.githubusercontent.com/69475751/132432562-f1743f91-b4a0-4eb5-ad8e-e61f96cf019a.jpg)
![dtstx-spring4](https://user-images.githubusercontent.com/69475751/132432563-0d6d5dce-6615-4d60-bed1-5301759c23cb.jpg)
![dtstx-spring5](https://user-images.githubusercontent.com/69475751/132432565-16f10b2d-2ee7-4895-aeb9-b6b455a866f8.jpg)
![dtstx-spring6](https://user-images.githubusercontent.com/69475751/132432570-51c26dc3-c353-48d1-a6c2-9ceb031fe301.jpg)
![dtstx-spring7](https://user-images.githubusercontent.com/69475751/132432571-8ae4937b-a182-4829-9cad-c31efe68c620.jpg)
![dtstx-spring8](https://user-images.githubusercontent.com/69475751/132432574-e408b917-f68b-4786-a780-dfb215fec6bd.jpg)
![dtstx-spring9](https://user-images.githubusercontent.com/69475751/132432577-c43ac839-ffbb-44dc-815e-d2a872561b97.jpg)
![dtstx-spring11](https://user-images.githubusercontent.com/69475751/132432583-60d4ca99-205d-448b-bf61-ab1ef4b57b06.jpg)
![dtstx-spring12](https://user-images.githubusercontent.com/69475751/132432586-fa9d9ee8-d075-499e-9040-00a45a825a9d.jpg)
![dtstx-spring13](https://user-images.githubusercontent.com/69475751/132432588-8dd9c8c0-58e3-4bc2-8fc0-209741185abd.JPG)
-- images removed by team --
![dtstx-spring18](https://user-images.githubusercontent.com/69475751/132432550-feec5cd1-39a8-480b-8c1f-2dd31f920d18.JPG)
![dtstx-spring19](https://user-images.githubusercontent.com/69475751/132432554-157b0d72-ea21-43ae-bf79-c02148ade2c7.JPG)
![dtstx-spring20](https://user-images.githubusercontent.com/69475751/132432557-fd073548-f3ae-450d-9e9a-ad400e047a9d.JPG)  
Attach the homework step II screenshots below:
-----------------------------------------
![dtstx-spring21](https://user-images.githubusercontent.com/69475751/132432697-5f04a853-12a1-4f17-ab23-e96dac8ca3cf.JPG)

**Comment by HadesArchitect** [comment]
Hey **Raphael**, great job! Congrats! Here is your badge! https://api.badgr.io/public/assertions/ZXc0Znj1SJKNYXk9qf7SgA

**Comment by SonicDMG** [comment]
Also, I had to remove a set of your images because they contained your Astra token. Please delete your token from the Astra UI so there are no security issues.

**Comment by raphaelgc** [comment]
@SonicDMG All tokens removed...
