### ISSUE TITLE
[HW] Prakash Choudhary

### ISSUE THREAD

**Issue by prakashcc** [datastaxdevs/workshop-spring-stargate#139]
Name: Prakash Choudhary
email: connect2prakashc@gmail.com

<img width="1680" alt="Screenshot 2021-09-11 at 1 09 50 AM" src="https://user-images.githubusercontent.com/16360540/132910610-11c1fc6a-2740-473e-9f85-7f1edb3ae559.png">
<img width="1680" alt="Screenshot 2021-09-11 at 1 08 20 AM" src="https://user-images.githubusercontent.com/16360540/132910617-b9bbb853-c36b-4b8f-8592-ee602ea99207.png">
<img width="1680" alt="Screenshot 2021-09-11 at 1 09 58 AM" src="https://user-images.githubusercontent.com/16360540/132910626-1e12a5f5-65cf-4296-8a88-920f7fbbf018.png">
<img width="1680" alt="Screenshot 2021-09-11 at 1 08 29 AM" src="https://user-images.githubusercontent.com/16360540/132910639-ad9c69cc-0395-4030-8ecb-e9ca2a4247a4.png">
<img width="1680" alt="Screenshot 2021-09-11 at 1 10 11 AM" src="https://user-images.githubusercontent.com/16360540/132910647-325af4ab-75da-44b7-815c-22c76b37b7f2.png">
<img width="1680" alt="Screenshot 2021-09-11 at 1 08 42 AM" src="https://user-images.githubusercontent.com/16360540/132910656-0182807a-4107-4b5a-9371-db416e17e944.png">
<img width="1680" alt="Screenshot 2021-09-11 at 1 10 20 AM" src="https://user-images.githubusercontent.com/16360540/132910661-0456281e-614b-448f-812f-d5458c65b575.png">
**Name:** <Prakash Choudhary><img width="1680" alt="Screenshot 2021-09-11 at 1 10 29 AM" src="https://user-images.githubusercontent.com/16360540/132910513-735337aa-d3ec-405c-99a9-c7540394291c.png">**Email:** <connect2prakashc@gmail.com>
**Linkedin Profile:** <https://www.linkedin.com/in/prakashcc/>

Attach the homework step I screenshots below:
-----------------------------------------

<img width="1680" alt="Screenshot 2021-09-11 at 1 10 36 AM" src="https://user-images.githubusercontent.com/16360540/132910550-47ef9f46-f48f-4c9c-a293-c774d826589c.png">
<img width="1680" alt="Screenshot 2021-09-11 at 1 08 53 AM" src="https://user-images.githubusercontent.com/16360540/132910558-a198e059-bb58-4477-9f1a-65aff98601ae.png">
<img width="1680" alt="Screenshot 2021-09-11 at 1 09 00 AM" src="https://user-images.githubusercontent.com/16360540/132910564-b85a660f-7380-458d-9dd5-9c91b0b2c737.png">
<img width="1680" alt="Screenshot 2021-09-11 at 1 09 07 AM" src="https://user-images.githubusercontent.com/16360540/132910569-b993796d-a863-459d-b5a0-7eb43398ee5c.png">
<img width="1680" alt="Screenshot 2021-09-11 at 1 10 54 AM" src="https://user-images.githubusercontent.com/16360540/132910570-2ffc6ca3-8efb-4fe9-bccb-6aac4fbac993.png">
<img width="1680" alt="Screenshot 2021-09-11 at 1 06 09 AM" src="https://user-images.githubusercontent.com/16360540/132910572-073096bd-e09f-40cd-b0ef-fcb982b5249c.png">
<img width="1680" alt="Screenshot 2021-09-11 at 1 06 47 AM" src="https://user-images.githubusercontent.com/16360540/132910576-7f0376b6-d243-403b-b203-2f3aae2f72c8.png">
<img width="1680" alt="Screenshot 2021-09-11 at 1 07 13 AM" src="https://user-images.githubusercontent.com/16360540/132910581-530a5e22-5c4d-48a2-9b5e-a8b043f7842b.png">
<img width="1680" alt="Screenshot 2021-09-11 at 1 09 30 AM" src="https://user-images.githubusercontent.com/16360540/132910583-5120dd59-a185-4a21-96e0-02dee51435ab.png">
<img width="1680" alt="Screenshot 2021-09-11 at 1 12 38 AM" src="https://user-images.githubusercontent.com/16360540/132910585-fa09c873-fc10-4d5a-91a1-72b7c51d5a20.png">
<img width="1680" alt="Screenshot 2021-09-11 at 1 08 06 AM" src="https://user-images.githubusercontent.com/16360540/132910592-c29c830f-adc8-4a0d-8bb9-9c9cf7f19bc8.png">
<img width="1680" alt="Screenshot 2021-09-11 at 1 08 14 AM" src="https://user-images.githubusercontent.com/16360540/132910607-b3490579-cffc-494d-b016-9728a282bff2.png">
<img width="1680" alt="Screenshot 2021-09-11 at 1 10 29 AM" src="https://user-images.githubusercontent.com/16360540/132910513-735337aa-d3ec-405c-99a9-c7540394291c.png">  
Attach the homework step II screenshots below:
-----------------------------------------

<SCREENSHOTS>
<img width="1680" alt="Screenshot 2021-09-11 at 1 35 45 AM" src="https://user-images.githubusercontent.com/16360540/132911463-41e6cfeb-2e0f-423a-b42a-04638de68fb1.png">

Made sampledoc model and spring

**Comment by prakashcc** [comment]
@HadesArchitect please let me know when you get a chance to review it.

**Comment by SonicDMG** [comment]
Hey there Prakash, thank you for your submission. Nice job getting the app correctly configured and deployed. The only thing we are missing is step 2 of the homework.
2. [Learn more about spring in the course](https://www.datastax.com/dev/spring) and complete scenario Build a Spring Boot REST Service at the bottom of the page and make a screenshot of the "congratulations" page.

Please post an image of the "completed" screen once finished

**Comment by SonicDMG** [comment]
Also, please provide your name and email so we can issue you a badge once complete. :D

**Comment by prakashcc** [comment]
<img width="1680" alt="Screenshot 2021-09-15 at 1 49 58 AM" src="https://user-images.githubusercontent.com/16360540/133328208-273484a7-ee6f-434e-a81b-cb052fa411c5.png">

Name - Prakash Choudhary
email- connect2prakashc@gmail.com

**Comment by prakashcc** [comment]
@SonicDMG  @HadesArchitect  I am interested in contributing to DataStax. Please help me in how I can contribute or any kind of work I can do to add value to the developer community.

**Comment by HadesArchitect** [comment]
Hey **Prakash Choudhary**, great job! Congrats! Here is your badge! https://api.badgr.io/public/assertions/Ub3CntfXTb2HjFgA97zogA

**Comment by SonicDMG** [comment]
> @SonicDMG @HadesArchitect I am interested in contributing to DataStax. Please help me in how I can contribute or any kind of work I can do to add value to the developer community.

Hey there, ack'ing this. I've passed your info along to the team to see if there is anything we might have on this front.

**Comment by prakashcc** [comment]
@SonicDMG @HadesArchitect Thank you. I am closing this thread
