### ISSUE TITLE
[HW] Arinjay Gangwar

### ISSUE THREAD

**Issue by arinjayg** [datastaxdevs/workshop-spring-stargate#18]
**Name:** Arinjay Gangwar
**Email:** arinjay.gangwar100@gmail.com
**Linkedin Profile:** <www.linkedin.com/in/arinjay-gangwar-1a3b93166>

Attach the homework step I screenshots below:
-----------------------------------------

![Screenshot 2021-06-23 234716](https://user-images.githubusercontent.com/76163860/123148508-f2890a80-d47d-11eb-8b59-2a9776230264.jpg)

![Screenshot 2021-06-23 234917](https://user-images.githubusercontent.com/76163860/123148896-53b0de00-d47e-11eb-943d-94504413024f.jpg)
  
Attach the homework step II screenshots below:
-----------------------------------------

![Screenshot 2021-06-23 234856](https://user-images.githubusercontent.com/76163860/123148792-32e88880-d47e-11eb-8495-adec91a53278.jpg)

**Comment by clun** [comment]
The app is working good job

**Comment by HadesArchitect** [comment]
Hey **Arinjay Gangwar**, great job! Congrats! Here is your badge! https://api.badgr.io/public/assertions/R1g9TKxmQOShhG-wmBDv7g
