### ISSUE TITLE
[HW] <Nikhil Ved>

### ISSUE THREAD

**Issue by NikhilVed** [datastaxdevs/workshop-spring-stargate#5]
**Name:** Nikhil Ved
**Email:** nvednl@gmail.com
**Linkedin Profile:** https://www.linkedin.com/in/nikhil-ved-78248544/

Attach the homework step I screenshots below:
-----------------------------------------
 
![stargate step2](https://user-images.githubusercontent.com/62669477/116532216-4d6c0e80-a8e0-11eb-9cd4-aa7e11b3d4f8.JPG)
![Stargate step3](https://user-images.githubusercontent.com/62669477/116532218-4e04a500-a8e0-11eb-808a-42825c1afd98.JPG)
![StargateExe01](https://user-images.githubusercontent.com/62669477/116532221-4e9d3b80-a8e0-11eb-832d-fe180ea46c29.JPG)
![Stargate](https://user-images.githubusercontent.com/62669477/116532222-4e9d3b80-a8e0-11eb-9396-390ac34430f4.JPG)
![stargate1](https://user-images.githubusercontent.com/62669477/116532224-4f35d200-a8e0-11eb-92d5-e36f72eac5fe.JPG)
![stargate2](https://user-images.githubusercontent.com/62669477/116532225-4f35d200-a8e0-11eb-82e0-5555253778eb.JPG)
![stargate3](https://user-images.githubusercontent.com/62669477/116532226-4f35d200-a8e0-11eb-92ca-77afbe34c3ae.JPG)
![stargateGitpod](https://user-images.githubusercontent.com/62669477/116532228-4fce6880-a8e0-11eb-9b5b-7ab6db083481.JPG)
![stargategitpod2](https://user-images.githubusercontent.com/62669477/116532229-4fce6880-a8e0-11eb-9ca8-8c1c52f8017d.JPG)
![stargatedocument](https://user-images.githubusercontent.com/62669477/116532232-5066ff00-a8e0-11eb-841d-916e8322979d.JPG)
![stargateexe1](https://user-images.githubusercontent.com/62669477/116532233-5066ff00-a8e0-11eb-8eba-713a3c333870.JPG)
![Stargatex2](https://user-images.githubusercontent.com/62669477/116532236-5066ff00-a8e0-11eb-9821-f83453e2d095.JPG)
![stargateex3](https://user-images.githubusercontent.com/62669477/116532237-50ff9580-a8e0-11eb-91c8-2571c5a796e0.JPG)

  
Attach the homework step II screenshots below:
-----------------------------------------

![homework stargate](https://user-images.githubusercontent.com/62669477/116532259-565ce000-a8e0-11eb-8687-2b4fee80825a.JPG)
![stargatehomework](https://user-images.githubusercontent.com/62669477/116532266-56f57680-a8e0-11eb-9170-2e8454439c7e.JPG)

**Comment by NikhilVed** [comment]
Completed the homework and labs while in the session.

**Comment by SonicDMG** [comment]
Thank you again for your submission, looks good. I see you have another submission as well so both are acknowledged.
