### ISSUE TITLE
[HW] <NAME>

### ISSUE THREAD

**Issue by juliann** [datastaxdevs/workshop-spring-stargate#56]
**Name:** Julian Nadarzy
**Email:** julian.nadarzy@gmail.com
**Linkedin Profile:** https://www.linkedin.com/in/julian-nadarzy-74b7b810

Attach the homework step I screenshots below:
-----------------------------------------

  
![a1](https://user-images.githubusercontent.com/1125748/131707928-b0f9e8af-10a2-475c-936b-a743eff13eb6.jpg)
![a2](https://user-images.githubusercontent.com/1125748/131707933-15c01836-4c2e-4d48-8ad3-bc16f073de1b.jpg)
![a3](https://user-images.githubusercontent.com/1125748/131707935-5eecc352-3fd2-44a7-bf6f-9a15d30ff1f9.jpg)
![a4](https://user-images.githubusercontent.com/1125748/131707938-3a65acda-ecc8-4143-9c13-bc9247e6c06c.jpg)
![a5](https://user-images.githubusercontent.com/1125748/131707939-06425f8c-ad22-4e4e-bf8b-bd7724a6a425.jpg)
![a6](https://user-images.githubusercontent.com/1125748/131707953-d3eadaea-2725-43d0-928c-af655be9be1a.jpg)
![a7](https://user-images.githubusercontent.com/1125748/131707958-9d38e6a3-3a72-4aae-932d-b3481c85cdab.jpg)

**Comment by HadesArchitect** [comment]
Hey **Julian Nadarzy**, great job! Congrats! Here is your badge! https://api.badgr.io/public/assertions/BL0MWiO3RtC_Klkse25wCg
