### ISSUE TITLE
[HW] Andrzej K

### ISSUE THREAD

**Issue by andrewprofile** [datastaxdevs/workshop-spring-stargate#84]
**Name:** Andrzej Kostrzewa
**Email:** drop@int.pl
**Linkedin Profile:** https://www.linkedin.com/in/andrewprofile/

Attach the homework step I screenshots below:
-----------------------------------------
![one](https://user-images.githubusercontent.com/7659096/131722608-4a775e28-4dd7-40d5-a386-a7d54135191a.png)
![two](https://user-images.githubusercontent.com/7659096/131722632-5f10b65d-3ea2-477e-9a56-d9aabf17bd27.png)

  
Attach the homework step II screenshots below:
-----------------------------------------
![three](https://user-images.githubusercontent.com/7659096/131722649-6160e1a3-0add-4400-8375-ed5cdd1a6916.png)

Thank you for the workshop, I learned new topics!

**Comment by clun** [comment]
Thank you for the great work, hope you enjoy the session !

**Comment by HadesArchitect** [comment]
Hey **Andrzej Kostrzewa**, great job! Congrats! Here is your badge! https://api.badgr.io/public/assertions/y9xNc73SQvuAW8tNw4KB2Q

**Comment by andrewprofile** [comment]
Thank you !
