### ISSUE TITLE
[HW] Saurabh Zinjad

### ISSUE THREAD

**Issue by Ztrimus** [datastaxdevs/workshop-spring-stargate#94]
**Name:** Saurabh Zinjad
**Email:** zinjadsaurabh18@gmail.com
**Linkedin Profile:** https://www.linkedin.com/in/saurabhzinjad

Attach the homework step I screenshots below:
-----------------------------------------
![Screenshot (151)](https://user-images.githubusercontent.com/20492451/131742119-f2d4bce2-fccf-4ac2-a7e8-5687a1d14697.png)
![Screenshot (152)](https://user-images.githubusercontent.com/20492451/131742169-c5ea8bee-3d84-4a7c-af60-4cff2e5a3514.png)
![Screenshot (153)](https://user-images.githubusercontent.com/20492451/131742160-4196aab1-aed6-4096-ac23-415c41ae9423.png)
![Screenshot (154)](https://user-images.githubusercontent.com/20492451/131742401-f2c833e7-7215-4903-bfb6-99feff3e75c6.png)
![Screenshot (155)](https://user-images.githubusercontent.com/20492451/131742405-1f0eca9c-c999-4019-958f-91f75c860f79.png)
![dataLoadStarted](https://user-images.githubusercontent.com/20492451/131742781-98417236-2836-4550-9563-79d5418dee98.jpg)
![dataLoadDone](https://user-images.githubusercontent.com/20492451/131742792-69aa3545-f93c-4e15-b37b-ce9eb4e9525e.jpg)
![Screenshot (156)](https://user-images.githubusercontent.com/20492451/131742409-c9e67d47-ffd4-4ce2-9205-d1b7c19b06b5.png)
-- image removed by team --
![Screenshot (159)](https://user-images.githubusercontent.com/20492451/131742423-f571f10d-be74-458e-b71f-a12d60d4fa4e.png)
![Screenshot (160)](https://user-images.githubusercontent.com/20492451/131742428-071ca19b-e690-4e0a-8f28-faa94008e141.png)
![Screenshot (161)](https://user-images.githubusercontent.com/20492451/131742431-1b5556bb-5a98-4acf-a136-019f5184a013.png)
![Screenshot (162)](https://user-images.githubusercontent.com/20492451/131742433-b5a6b9b1-6da3-4c80-b7ad-89eda12cf575.png)
![Screenshot (163)](https://user-images.githubusercontent.com/20492451/131742436-07eb86c8-233d-4bfa-b1c6-21b3f44fba09.png)
![Screenshot (164)](https://user-images.githubusercontent.com/20492451/131742442-b8be3e58-ec35-4e25-a4e4-983f80751b31.png)
![Screenshot (165)](https://user-images.githubusercontent.com/20492451/131742444-4b1e4e7e-bccb-4299-bda4-7126c7e3c080.png)
![Screenshot (166)](https://user-images.githubusercontent.com/20492451/131742448-0d9adc60-4a03-46f4-ab71-081db1215d1b.png)
![Screenshot (167)](https://user-images.githubusercontent.com/20492451/131742457-c13056f3-24a5-448e-aeda-fe0a72e479fc.png)
![Screenshot (168)](https://user-images.githubusercontent.com/20492451/131742472-498cd22d-c558-4682-a8d7-67ac80072141.png)
-- images removed by team --
![Screenshot (172)](https://user-images.githubusercontent.com/20492451/131742390-d3c39785-cf3d-49d9-8059-21870d33a583.png)
![Screenshot (173)](https://user-images.githubusercontent.com/20492451/131742395-89355a47-6420-48f9-9fdb-f61e89a30e7b.png)
![Screenshot (174)](https://user-images.githubusercontent.com/20492451/131742399-61ebf06f-670e-4385-87d6-94c8a8bdf273.png)

  
Attach the homework step II screenshots below:
-----------------------------------------
![Screenshot (176)](https://user-images.githubusercontent.com/20492451/131742537-f1a3dd02-74c9-40fc-9639-ef7a4a45b266.png)

**Comment by HadesArchitect** [comment]
Hey **Saurabh Zinjad**, great job! Congrats! Here is your badge! https://api.badgr.io/public/assertions/XMg5tJz8TOORVd4Nf-OwLA

**Comment by SonicDMG** [comment]
Also, I had to remove a set of your images because they contained your Astra token. Please delete your token from the Astra UI so there are no security issues.

**Comment by Ztrimus** [comment]
> Also, I had to remove a set of your images because they contained your Astra token. Please delete your token from the Astra UI so there are no security issues.

Yes, I removed the token, And I'm also closing this issue.

Thank you again @SonicDMG for such a wonderful session
